export const categoryOptions = [
  { value: 'Entertainment', label: 'Entertainment' },
  { value: 'Programming', label: 'Programming' },
  { value: 'Personal', label: 'Personal' },
  { value: 'Science', label: 'Science' },
  { value: 'Technology', label: 'Technology' },
  { value: 'Health', label: 'Health' },
  { value: 'Arts', label: 'Arts' },
  { value: 'History', label: 'History' },
  { value: 'Food & Cooking', label: 'Food & Cooking' },
  { value: 'Travel', label: 'Travel' },
  { value: 'Literature', label: 'Literature' },
  { value: 'Fashion & Beauty', label: 'Fashion & Beauty' },
  { value: 'Psychology', label: 'Psychology' },
  { value: 'Philosophy', label: 'Philosophy' },
  { value: 'Religion & Spirituality', label: 'Religion & Spirituality' },
  { value: 'Environment & Sustainability', label: 'Environment & Sustainability' },
  { value: 'Politics & Government', label: 'Politics & Government' },
  { value: 'Education', label: 'Education' },
  { value: 'Finance & Economics', label: 'Finance & Economics' },
  { value: 'Automotive', label: 'Automotive' },
  { value: 'Home & Garden', label: 'Home & Garden' },
  { value: 'Parenting & Family', label: 'Parenting & Family' },
  { value: 'Astronomy', label: 'Astronomy' },
  { value: 'Law & Legal', label: 'Law & Legal' },
  { value: 'DIY & Crafts', label: 'DIY & Crafts' },
  { value: 'Relationships & Dating', label: 'Relationships & Dating' },
  { value: 'Pets & Animals', label: 'Pets & Animals' },
  { value: 'Gaming', label: 'Gaming' },
  { value: 'Music', label: 'Music' },
  { value: 'Spirituality & Meditation', label: 'Spirituality & Meditation' },
  { value: 'Fitness & Exercise', label: 'Fitness & Exercise' },
  { value: 'Languages & Linguistics', label: 'Languages & Linguistics' },
  { value: 'Sports', label: 'Sports' },
  { value: 'Engineering', label: 'Engineering' },
  { value: 'Medical', label: 'Medical' },
  { value: 'Business', label: 'Business' },
  { value: 'Design', label: 'Design' },
  { value: 'Architecture', label: 'Architecture' },
  { value: 'Outdoor Activities', label: 'Outdoor Activities' },
  { value: 'Hobbies', label: 'Hobbies' },
  { value: 'Film & Cinema', label: 'Film & Cinema' },
  { value: 'Photography', label: 'Photography' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Human Resources', label: 'Human Resources' },
  { value: 'Weather', label: 'Weather' },
  { value: 'Cuisine', label: 'Cuisine' },
  { value: 'Volunteering', label: 'Volunteering' },
  { value: 'Cryptography', label: 'Cryptography' },
  { value: 'Sociology', label: 'Sociology' },
  { value: 'Futurism', label: 'Futurism' },
  { value: 'Mythology', label: 'Mythology' },
  { value: 'Adventure', label: 'Adventure' },
  { value: 'Craft Beer', label: 'Craft Beer' },
  { value: 'Fitness & Wellness', label: 'Fitness & Wellness' },
  { value: 'Self-Improvement', label: 'Self-Improvement' },
  { value: 'Robotics', label: 'Robotics' },
  { value: 'Social Media', label: 'Social Media' },
  { value: 'Interior Design', label: 'Interior Design' },
  { value: 'Parenting Styles', label: 'Parenting Styles' },
  { value: 'Green Living', label: 'Green Living' },
  { value: 'Virtual Reality', label: 'Virtual Reality' },
  { value: 'Urban Planning', label: 'Urban Planning' },
  { value: 'Magic & Illusion', label: 'Magic & Illusion' },
  { value: 'Astrology', label: 'Astrology' },
  { value: 'Cryptocurrency', label: 'Cryptocurrency' },
  { value: 'Extraterrestrial Life', label: 'Extraterrestrial Life' },
  { value: 'Animation', label: 'Animation' },
  { value: 'Conspiracy Theories', label: 'Conspiracy Theories' },
  { value: 'Online Communities', label: 'Online Communities' },
  { value: 'Ethics', label: 'Ethics' },
  { value: 'Adventure Travel', label: 'Adventure Travel' },
  { value: 'Antiques & Collectibles', label: 'Antiques & Collectibles' },
  { value: 'Biohacking', label: 'Biohacking' },
  { value: 'Urban Exploration', label: 'Urban Exploration' },
  { value: 'Survival Skills', label: 'Survival Skills' },
  { value: 'Paranormal Phenomena', label: 'Paranormal Phenomena' },
  { value: 'Outdoor Survival', label: 'Outdoor Survival' },
  { value: 'Mindfulness', label: 'Mindfulness' },
  { value: 'Ancient Civilizations', label: 'Ancient Civilizations' },
  { value: 'Exotic Pets', label: 'Exotic Pets' },
  { value: 'DIY Electronics', label: 'DIY Electronics' },
  { value: 'Science Fiction', label: 'Science Fiction' },
  { value: 'Alternative Energy', label: 'Alternative Energy' },
  { value: 'Extreme Sports', label: 'Extreme Sports' },
  { value: 'Sustainable Living', label: 'Sustainable Living' },
  { value: 'Crafting', label: 'Crafting' },
  { value: 'Virtual Communities', label: 'Virtual Communities' },
  { value: 'Disaster Preparedness', label: 'Disaster Preparedness' },
  { value: 'Mental Health', label: 'Mental Health' },
  { value: 'Performance Arts', label: 'Performance Arts' },
  { value: 'Herbalism', label: 'Herbalism' },
  { value: 'Marine Biology', label: 'Marine Biology' },
]

export const occupationOptions = [
  { value: 'Software Engineer', label: 'Software Engineer' },
  { value: 'Data Analyst', label: 'Data Analyst' },
  { value: 'Company', label: 'Company' },
  { value: 'Educational Organization', label: 'Educational Organization' },
  { value: 'Student', label: 'Student' },
  { value: 'Marketing Manager', label: 'Marketing Manager' },
  { value: 'Graphic Designer', label: 'Graphic Designer' },
  { value: 'Financial Analyst', label: 'Financial Analyst' },
  { value: 'Registered Nurse', label: 'Registered Nurse' },
  { value: 'Sales Associate', label: 'Sales Associate' },
  { value: 'Customer Service Representative', label: 'Customer Service Representative' },
  { value: 'Mechanical Engineer', label: 'Mechanical Engineer' },
  { value: 'Teacher', label: 'Teacher' },
  { value: 'Accountant', label: 'Accountant' },
  { value: 'Administrative Assistant', label: 'Administrative Assistant' },
  { value: 'Electrician', label: 'Electrician' },
  { value: 'Project Manager', label: 'Project Manager' },
  { value: 'Physician Assistant', label: 'Physician Assistant' },
  { value: 'Web Developer', label: 'Web Developer' },
  { value: 'Human Resources Manager', label: 'Human Resources Manager' },
  { value: 'Mechanic', label: 'Mechanic' },
  { value: 'Pharmacist', label: 'Pharmacist' },
  { value: 'Software Developer', label: 'Software Developer' },
  { value: 'Operations Manager', label: 'Operations Manager' },
  { value: 'Dental Hygienist', label: 'Dental Hygienist' },
  { value: 'Real Estate Agent', label: 'Real Estate Agent' },
  { value: 'Nurse Practitioner', label: 'Nurse Practitioner' },
  { value: 'Data Scientist', label: 'Data Scientist' },
  { value: 'Executive Assistant', label: 'Executive Assistant' },
  { value: 'Social Media Manager', label: 'Social Media Manager' },
  { value: 'Chef', label: 'Chef' },
  { value: 'Civil Engineer', label: 'Civil Engineer' },
  { value: 'Physical Therapist', label: 'Physical Therapist' },
  { value: 'Dentist', label: 'Dentist' },
  { value: 'Retail Sales Associate', label: 'Retail Sales Associate' },
  { value: 'Network Administrator', label: 'Network Administrator' },
  { value: 'Business Analyst', label: 'Business Analyst' },
  { value: 'Logistics Manager', label: 'Logistics Manager' },
  { value: 'Occupational Therapist', label: 'Occupational Therapist' },
  { value: 'Public Relations Specialist', label: 'Public Relations Specialist' },
  { value: 'Journalist', label: 'Journalist' },
  { value: 'Interior Designer', label: 'Interior Designer' },
  { value: 'Architect', label: 'Architect' },
  { value: 'Insurance Agent', label: 'Insurance Agent' },
  { value: 'Art Director', label: 'Art Director' },
  { value: 'Pharmacy Technician', label: 'Pharmacy Technician' },
  { value: 'Mechanical Designer', label: 'Mechanical Designer' },
  { value: 'Security Guard', label: 'Security Guard' },
  { value: 'Investment Banker', label: 'Investment Banker' },
  { value: 'Copywriter', label: 'Copywriter' },
  { value: 'Veterinarian', label: 'Veterinarian' },
  { value: 'Operations Analyst', label: 'Operations Analyst' },
  { value: 'Digital Marketing Manager', label: 'Digital Marketing Manager' },
  { value: 'Customer Success Manager', label: 'Customer Success Manager' },
  { value: 'Pilot', label: 'Pilot' },
  { value: 'Biomedical Engineer', label: 'Biomedical Engineer' },
  { value: 'Mechanical Technician', label: 'Mechanical Technician' },
  { value: 'Receptionist', label: 'Receptionist' },
  { value: 'Software Architect', label: 'Software Architect' },
  { value: 'Financial Advisor', label: 'Financial Advisor' },
  { value: 'Event Planner', label: 'Event Planner' },
  { value: 'Sales Manager', label: 'Sales Manager' },
  { value: 'Aircraft Mechanic', label: 'Aircraft Mechanic' },
  { value: 'Electrical Engineer', label: 'Electrical Engineer' },
  { value: 'Paralegal', label: 'Paralegal' },
  { value: 'Civil Engineering Technician', label: 'Civil Engineering Technician' },
  { value: 'Personal Trainer', label: 'Personal Trainer' },
  { value: 'Medical Assistant', label: 'Medical Assistant' },
  { value: 'Software Tester', label: 'Software Tester' },
  { value: 'Investment Analyst', label: 'Investment Analyst' },
  { value: 'Fashion Designer', label: 'Fashion Designer' },
  { value: 'Insurance Underwriter', label: 'Insurance Underwriter' },
  { value: 'Medical Technologist', label: 'Medical Technologist' },
  { value: 'Chemist', label: 'Chemist' },
  { value: 'Systems Analyst', label: 'Systems Analyst' },
  { value: 'Airline Pilot', label: 'Airline Pilot' },
  { value: 'Civil Engineering Technologist', label: 'Civil Engineering Technologist' },
  { value: 'Investment Manager', label: 'Investment Manager' },
  { value: 'Medical Laboratory Technician', label: 'Medical Laboratory Technician' },
  { value: 'Human Resources Generalist', label: 'Human Resources Generalist' },
  { value: 'Electrical Technician', label: 'Electrical Technician' },
  { value: 'Environmental Engineer', label: 'Environmental Engineer' },
  { value: 'Quality Control Inspector', label: 'Quality Control Inspector' },
  { value: 'Physical Therapy Assistant', label: 'Physical Therapy Assistant' },
  { value: 'Marketing Specialist', label: 'Marketing Specialist' },
  { value: 'Financial Planner', label: 'Financial Planner' },
  { value: 'Web Designer', label: 'Web Designer' },
  { value: 'Technical Writer', label: 'Technical Writer' },
  { value: 'Investment Advisor', label: 'Investment Advisor' },
  { value: 'Mechanical Engineering Technician', label: 'Mechanical Engineering Technician' },
  { value: 'Biomedical Technologist', label: 'Biomedical Technologist' },
  { value: 'Maintenance Technician', label: 'Maintenance Technician' },
]

export const countryOptions = [
  { value: 'Afghanistan', label: 'Afghanistan' },
  { value: 'Albania', label: 'Albania' },
  { value: 'Algeria', label: 'Algeria' },
  { value: 'Andorra', label: 'Andorra' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Armenia', label: 'Armenia' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaijan', label: 'Azerbaijan' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Belarus', label: 'Belarus' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Belize', label: 'Belize' },
  { value: 'Benin', label: 'Benin' },
  { value: 'Bhutan', label: 'Bhutan' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'Brunei', label: 'Brunei' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Burkina Faso', label: 'Burkina Faso' },
  { value: 'Burundi', label: 'Burundi' },
  { value: 'Cabo Verde', label: 'Cabo Verde' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Cameroon', label: 'Cameroon' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Central African Republic', label: 'Central African Republic' },
  { value: 'Chad', label: 'Chad' },
  { value: 'Chile', label: 'Chile' },
  { value: 'China', label: 'China' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Comoros', label: 'Comoros' },
  { value: 'Congo', label: 'Congo' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Cyprus', label: 'Cyprus' },
  { value: 'Czech Republic', label: 'Czech Republic' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Djibouti', label: 'Djibouti' },
  { value: 'Dominica', label: 'Dominica' },
  { value: 'Dominican Republic', label: 'Dominican Republic' },
  { value: 'East Timor', label: 'East Timor' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
  { value: 'Eritrea', label: 'Eritrea' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Eswatini', label: 'Eswatini' },
  { value: 'Ethiopia', label: 'Ethiopia' },
  { value: 'Fiji', label: 'Fiji' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'Gabon', label: 'Gabon' },
  { value: 'Gambia', label: 'Gambia' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Grenada', label: 'Grenada' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Guinea', label: 'Guinea' },
  { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Haiti', label: 'Haiti' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'India', label: 'India' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Iran', label: 'Iran' },
  { value: 'Iraq', label: 'Iraq' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Kazakhstan', label: 'Kazakhstan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Kiribati', label: 'Kiribati' },
  { value: 'Korea, North', label: 'Korea, North' },
  { value: 'Korea, South', label: 'Korea, South' },
  { value: 'Kosovo', label: 'Kosovo' },
  { value: 'Kuwait', label: 'Kuwait' },
  { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
  { value: 'Laos', label: 'Laos' },
  { value: 'Latvia', label: 'Latvia' },
  { value: 'Lebanon', label: 'Lebanon' },
  { value: 'Lesotho', label: 'Lesotho' },
  { value: 'Liberia', label: 'Liberia' },
  { value: 'Libya', label: 'Libya' },
  { value: 'Liechtenstein', label: 'Liechtenstein' },
  { value: 'Lithuania', label: 'Lithuania' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Madagascar', label: 'Madagascar' },
  { value: 'Malawi', label: 'Malawi' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Mali', label: 'Mali' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Marshall Islands', label: 'Marshall Islands' },
  { value: 'Mauritania', label: 'Mauritania' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Mexico', label: 'Mexico' },
  { value: 'Micronesia', label: 'Micronesia' },
  { value: 'Moldova', label: 'Moldova' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Montenegro', label: 'Montenegro' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Mozambique', label: 'Mozambique' },
  { value: 'Myanmar', label: 'Myanmar' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Niger', label: 'Niger' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'North Macedonia', label: 'North Macedonia' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Palau', label: 'Palau' },
  { value: 'Palestinian State', label: 'Palestinian State' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Papua New Guinea', label: 'Papua New Guinea' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Peru', label: 'Peru' },
  { value: 'Philippines', label: 'Philippines' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Romania', label: 'Romania' },
  { value: 'Russia', label: 'Russia' },
  { value: 'Rwanda', label: 'Rwanda' },
  { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
  { value: 'Saint Lucia', label: 'Saint Lucia' },
  { value: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines' },
  { value: 'Samoa', label: 'Samoa' },
  { value: 'San Marino', label: 'San Marino' },
  { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Senegal', label: 'Senegal' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Seychelles', label: 'Seychelles' },
  { value: 'Sierra Leone', label: 'Sierra Leone' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Slovenia', label: 'Slovenia' },
  { value: 'Solomon Islands', label: 'Solomon Islands' },
  { value: 'Somalia', label: 'Somalia' },
  { value: 'South Africa', label: 'South Africa' },
  { value: 'South Sudan', label: 'South Sudan' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Sudan', label: 'Sudan' },
  { value: 'Suriname', label: 'Suriname' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Syria', label: 'Syria' },
  { value: 'Taiwan', label: 'Taiwan' },
  { value: 'Tajikistan', label: 'Tajikistan' },
  { value: 'Tanzania', label: 'Tanzania' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Togo', label: 'Togo' },
  { value: 'Tonga', label: 'Tonga' },
  { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
  { value: 'Tunisia', label: 'Tunisia' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'Turkmenistan', label: 'Turkmenistan' },
  { value: 'Tuvalu', label: 'Tuvalu' },
  { value: 'Uganda', label: 'Uganda' },
  { value: 'Ukraine', label: 'Ukraine' },
  { value: 'United Arab Emirates', label: 'United Arab Emirates' },
  { value: 'United Kingdom', label: 'United Kingdom' },
  { value: 'United States', label: 'United States' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Uzbekistan', label: 'Uzbekistan' },
  { value: 'Vanuatu', label: 'Vanuatu' },
  { value: 'Vatican City', label: 'Vatican City' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Vietnam', label: 'Vietnam' },
  { value: 'Yemen', label: 'Yemen' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Zimbabwe', label: 'Zimbabwe' },
]

export const getRateAverage = (reviews: any[]) => {
  const total = reviews.reduce((accumulator, currentValue) => accumulator + currentValue.rate, 0)
  const average = total / reviews.length

  if (average) {
    return average
  } else {
    return 0
  }
}
