export const categoryOptions = [
  { value: 'Entertainment', label: 'Entertainment' },
  { value: 'Programming', label: 'Programming' },
  { value: 'Personal', label: 'Personal' },
  { value: 'Science', label: 'Science' },
  { value: 'Technology', label: 'Technology' },
  { value: 'Health', label: 'Health' },
  { value: 'Arts', label: 'Arts' },
  { value: 'History', label: 'History' },
  { value: 'Food & Cooking', label: 'Food & Cooking' },
  { value: 'Travel', label: 'Travel' },
  { value: 'Literature', label: 'Literature' },
  { value: 'Fashion & Beauty', label: 'Fashion & Beauty' },
  { value: 'Psychology', label: 'Psychology' },
  { value: 'Philosophy', label: 'Philosophy' },
  { value: 'Religion & Spirituality', label: 'Religion & Spirituality' },
  { value: 'Environment & Sustainability', label: 'Environment & Sustainability' },
  { value: 'Politics & Government', label: 'Politics & Government' },
  { value: 'Education', label: 'Education' },
  { value: 'Finance & Economics', label: 'Finance & Economics' },
  { value: 'Automotive', label: 'Automotive' },
  { value: 'Home & Garden', label: 'Home & Garden' },
  { value: 'Parenting & Family', label: 'Parenting & Family' },
  { value: 'Astronomy', label: 'Astronomy' },
  { value: 'Law & Legal', label: 'Law & Legal' },
  { value: 'DIY & Crafts', label: 'DIY & Crafts' },
  { value: 'Relationships & Dating', label: 'Relationships & Dating' },
  { value: 'Pets & Animals', label: 'Pets & Animals' },
  { value: 'Gaming', label: 'Gaming' },
  { value: 'Music', label: 'Music' },
  { value: 'Spirituality & Meditation', label: 'Spirituality & Meditation' },
  { value: 'Fitness & Exercise', label: 'Fitness & Exercise' },
  { value: 'Languages & Linguistics', label: 'Languages & Linguistics' },
  { value: 'Sports', label: 'Sports' },
  { value: 'Engineering', label: 'Engineering' },
  { value: 'Medical', label: 'Medical' },
  { value: 'Business', label: 'Business' },
  { value: 'Design', label: 'Design' },
  { value: 'Architecture', label: 'Architecture' },
  { value: 'Outdoor Activities', label: 'Outdoor Activities' },
  { value: 'Hobbies', label: 'Hobbies' },
  { value: 'Film & Cinema', label: 'Film & Cinema' },
  { value: 'Photography', label: 'Photography' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Human Resources', label: 'Human Resources' },
  { value: 'Weather', label: 'Weather' },
  { value: 'Cuisine', label: 'Cuisine' },
  { value: 'Volunteering', label: 'Volunteering' },
  { value: 'Cryptography', label: 'Cryptography' },
  { value: 'Sociology', label: 'Sociology' },
  { value: 'Futurism', label: 'Futurism' },
  { value: 'Mythology', label: 'Mythology' },
  { value: 'Adventure', label: 'Adventure' },
  { value: 'Craft Beer', label: 'Craft Beer' },
  { value: 'Fitness & Wellness', label: 'Fitness & Wellness' },
  { value: 'Self-Improvement', label: 'Self-Improvement' },
  { value: 'Robotics', label: 'Robotics' },
  { value: 'Social Media', label: 'Social Media' },
  { value: 'Interior Design', label: 'Interior Design' },
  { value: 'Parenting Styles', label: 'Parenting Styles' },
  { value: 'Green Living', label: 'Green Living' },
  { value: 'Virtual Reality', label: 'Virtual Reality' },
  { value: 'Urban Planning', label: 'Urban Planning' },
  { value: 'Magic & Illusion', label: 'Magic & Illusion' },
  { value: 'Astrology', label: 'Astrology' },
  { value: 'Cryptocurrency', label: 'Cryptocurrency' },
  { value: 'Extraterrestrial Life', label: 'Extraterrestrial Life' },
  { value: 'Animation', label: 'Animation' },
  { value: 'Conspiracy Theories', label: 'Conspiracy Theories' },
  { value: 'Online Communities', label: 'Online Communities' },
  { value: 'Ethics', label: 'Ethics' },
  { value: 'Adventure Travel', label: 'Adventure Travel' },
  { value: 'Antiques & Collectibles', label: 'Antiques & Collectibles' },
  { value: 'Biohacking', label: 'Biohacking' },
  { value: 'Urban Exploration', label: 'Urban Exploration' },
  { value: 'Survival Skills', label: 'Survival Skills' },
  { value: 'Paranormal Phenomena', label: 'Paranormal Phenomena' },
  { value: 'Outdoor Survival', label: 'Outdoor Survival' },
  { value: 'Mindfulness', label: 'Mindfulness' },
  { value: 'Ancient Civilizations', label: 'Ancient Civilizations' },
  { value: 'Exotic Pets', label: 'Exotic Pets' },
  { value: 'DIY Electronics', label: 'DIY Electronics' },
  { value: 'Science Fiction', label: 'Science Fiction' },
  { value: 'Alternative Energy', label: 'Alternative Energy' },
  { value: 'Extreme Sports', label: 'Extreme Sports' },
  { value: 'Sustainable Living', label: 'Sustainable Living' },
  { value: 'Crafting', label: 'Crafting' },
  { value: 'Virtual Communities', label: 'Virtual Communities' },
  { value: 'Disaster Preparedness', label: 'Disaster Preparedness' },
  { value: 'Mental Health', label: 'Mental Health' },
  { value: 'Performance Arts', label: 'Performance Arts' },
  { value: 'Herbalism', label: 'Herbalism' },
  { value: 'Marine Biology', label: 'Marine Biology' },
]
